Nikita/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dormitory.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dormitory/urls.py
from django.urls import path

from dormitory.views import NewsListView, PointsHistoryListView, student_dossier_view, PointsHistorySortsListView

urlpatterns = [
    path('', NewsListView.as_view(), name='main'),
    path('students/', PointsHistoryListView.as_view(), name='student_list'),
    path('student/<int:student_id>/points_history/', PointsHistoryListView.as_view(), name='points_history_list'),
    path('student/<int:student_id>/', student_dossier_view, name='student-dossier'),
    path('statistics/', PointsHistorySortsListView.as_view(), name='student-statistics'),

]

dormitory/models.py
from django.db import models


class Dormitory(models.Model):
    """Модель общежития."""
    name = models.CharField(max_length=255, unique=True, verbose_name='Название')
    address = models.CharField(max_length=255, verbose_name='Адрес', blank=True, null=True)
    phone = models.CharField(max_length=255, verbose_name='Телефон', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Общежитие'
        verbose_name_plural = 'Общежития'


class Student(models.Model):
    """Модель студента."""
    full_name = models.CharField(max_length=255, verbose_name='ФИО')
    dormitory = models.ForeignKey(Dormitory, on_delete=models.CASCADE, verbose_name='Общежитие')
    institute = models.CharField(max_length=255, verbose_name='Институт', blank=True, null=True)
    group = models.CharField(max_length=255, verbose_name='Группа', blank=True, null=True)
    room = models.CharField(max_length=255, verbose_name='Комната', blank=True, null=True)
    admin_points = models.IntegerField(default=0, verbose_name='Административные баллы', blank=True, null=True)
    sso_points = models.IntegerField(default=0, verbose_name='ССО баллы', blank=True, null=True)

    def __str__(self):
        return self.full_name

    def total_points(self):
        return self.admin_points + self.sso_points

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'


class Event(models.Model):
    """Модель события."""
    CHOISES = (
        ('admin', 'Административное'),
        ('sso', 'ССО'),
    )
    name = models.CharField(max_length=255, unique=True, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    points = models.IntegerField(default=0, verbose_name='Баллы')
    event_type = models.CharField(max_length=255, choices=CHOISES, verbose_name='Тип события')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'


class PointsHistory(models.Model):
    """Модель истории баллов."""
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='Студент', related_name='pointshistory')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name='Событие')
    date = models.DateTimeField(verbose_name='Дата')

    def __str__(self):
        return f'{self.student} - {self.event}'

    def save(self, *args, **kwargs):
        """Переопределяем метод сохранения записи в истории баллов."""
        # Если это новая запись в истории баллов
        if not self.pk:
            # Обновляем баллы студента в зависимости от типа события
            if self.event.event_type == 'admin':
                self.student.admin_points += self.event.points
            elif self.event.event_type == 'sso':
                self.student.sso_points += self.event.points
            self.student.save()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'История баллов'
        verbose_name_plural = 'История баллов'


class News(models.Model):
    """Модель новостей."""
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание')
    date = models.DateTimeField(auto_now_add=True)
    dormitory = models.ForeignKey(Dormitory, on_delete=models.CASCADE, verbose_name='Общежитие')
    images = models.ImageField(upload_to='news/', verbose_name='Изображения', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

dormitory/views.py
from pprint import pprint

from django.db.models import ExpressionWrapper, IntegerField, F, Sum, Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from dormitory.models import News, PointsHistory, Student, Dormitory


class NewsListView(ListView):
    """Выдача списка новостей."""
    model = News
    template_name = 'news.html'

    def get_queryset(self):
        return News.objects.order_by('-date')


class PointsHistoryListView(ListView):
    """Выдача истории баллов для конкретного студента."""
    model = PointsHistory
    template_name = 'students.html'  # Убедитесь, что это правильный шаблон

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        students = Student.objects.all()
        for student in students:
            student.history = PointsHistory.objects.filter(student=student)
        context['students'] = students
        pprint(context)
        return context


def student_dossier_view(request, student_id):
    """Просмотр досье студента."""
    student = get_object_or_404(Student, id=student_id)
    points_history = PointsHistory.objects.filter(student=student).select_related('event')

    # Аннотируем объект студента, добавляя сумму баллов по типам событий
    student = Student.objects.filter(id=student_id).annotate(
        total_admin_points=Sum('pointshistory__event__points', filter=Q(pointshistory__event__event_type='admin')),
        total_sso_points=Sum('pointshistory__event__points', filter=Q(pointshistory__event__event_type='sso'))
    ).first()

    total_students = Student.objects.count()
    middle_index = total_students // 2
    red_threshold = total_students - 10

    # Определение позиции студента
    ranking = Student.objects.annotate(
        total_points=Sum('pointshistory__event__points')
    ).order_by('-total_points').values_list('id', flat=True)
    position = list(ranking).index(student.id) + 1  # Indexing from 1

    context = {
        'student': student,
        'points_history': points_history,
        'ranking_position': position,
        'total_students': total_students,
        'middle_index': middle_index,
        'red_threshold': red_threshold,
    }
    return render(request, 'student_dossier.html', context)


class PointsHistorySortsListView(ListView):
    """Выдача истории баллов для конкретного студента."""
    model = Student
    template_name = 'statistics.html'
    context_object_name = 'students'

    def get_queryset(self):
        """Фильтрация студентов по общежитию, группе и комнате."""
        queryset = Student.objects.annotate(
            total_admin_points=Sum('pointshistory__event__points', filter=Q(pointshistory__event__event_type='admin')),
            total_sso_points=Sum('pointshistory__event__points', filter=Q(pointshistory__event__event_type='sso')),
            total_points=F('total_admin_points') + F('total_sso_points')
        ).order_by('-total_points')

        dormitory = self.request.GET.get('dormitory')
        group = self.request.GET.get('group')
        room = self.request.GET.get('room')

        if dormitory:
            queryset = queryset.filter(dormitory__id=dormitory)
        if group:
            queryset = queryset.filter(group=group)
        if room:
            queryset = queryset.filter(room=room)

        return queryset

    def get_context_data(self, **kwargs):
        """Добавление списка общежитий в контекст."""
        context = super().get_context_data(**kwargs)
        context['dormitories'] = Dormitory.objects.all()  # Добавляем список общежитий
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новости общежития</title>
    <!-- Подключение Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Комплекс</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
 <!-- Bootstrap Icons -->
<link href="{% static '/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">

<!-- AOS Animate On Scroll Library -->
<link href="{% static '/vendor/aos/aos.css' %}" rel="stylesheet">

<!-- GLightbox CSS -->
<link href="{% static '/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

<!-- Swiper JS CSS Bundle -->
<link href="{% static '/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

<!-- Main CSS File -->
<link href="{% static '/css/main.css' %}" rel="stylesheet">


  <!-- =======================================================
  * Template Name: Mentor
  * Template URL: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/
  * Updated: May 04 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

      <a href="{% url 'main' %}" class="logo d-flex align-items-center me-auto">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Комплекс</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="index.html" class="active">Главная</a></li>
          <li><a href="{% url 'student_list' %}">Студенты</a></li>
          <li><a href="{% url 'student-statistics' %}">Статистика</a></li>
          
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

      <a class="btn-getstarted" href="{% url 'admin:index' %}">Панель</a>

    </div>
  </header>
  
{% block content %}
{% endblock %}

<!-- Подключение Bootstrap 5 JS и Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
<footer id="footer" class="footer position-relative">

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="index.html" class="logo d-flex align-items-center">
            <span class="sitename">Mentor</span>
          </a>
          <div class="footer-contact pt-3">
            <p>A108 Adam Street</p>
            <p>New York, NY 535022</p>
            <p class="mt-3"><strong>Phone:</strong> <span>+1 5589 55488 55</span></p>
            <p><strong>Email:</strong> <span>info@example.com</span></p>
          </div>
          <div class="social-links d-flex mt-4">
            <a href=""><i class="bi bi-twitter"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="{% url 'main' %}">Главная</a></li>
            <li><a href="{% url 'student-statistics' %}">Статистика</a></li>
            <li><a href="{% url 'student_list' %}">Студенты</a></li>
            <li><a href="{% url 'admin:index' %}">Админка</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Остальные сервисы</h4>
          <ul>
            <li><a href="#">Мой дневник</a></li>
            <li><a href="#">Моя библиотека</a></li>
            <li><a href="#">Мой спорт</a></li>
          </ul>
        </div>

        <div class="col-lg-4 col-md-12 footer-newsletter">
          <h4>Противодействия коррупции</h4>
          <p>Коррупция подрывает доверие к государственным институтам, ухудшает качество жизни, способствует социальной несправедливости и препятствует устойчивому развитию.</p>

        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">Mentor</strong> <span>Тут ваша компания</span></p>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->

<script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static '/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static '/vendor/aos/aos.js' %}"></script>
<script src="{% static '/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static '/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static '/vendor/swiper/swiper-bundle.min.js' %}"></script>

<!-- Main JS File -->
<script src="{% static '/js/main.js' %}"></script>


</body>

</html>

templates/news.html
{% extends 'base.html' %}
{% load static %}  <!-- Загрузка статических файлов, если это необходимо -->

{% block content %}
    <style>
    
    .card-img {
  height: 200px; /* Установите желаемую высоту изображений */
  overflow: hidden; /* Обрезка изображения, если оно выходит за пределы блока */
}
.news-card {
    margin-bottom: 30px; /* Настройте значение по вашему желанию */
}
.card-img img {
  width: 100%; /* Ширина изображения равна ширине контейнера */
  height: 100%; /* Высота изображения равна высоте контейнера */
  object-fit: cover; /* Обеспечивает заполнение контейнера изображением без искажений */
  transition: transform 0.3s ease; /* Плавность анимации */
}

.card-img:hover img {
  transform: scale(1.1); /* Увеличение изображения при наведении */
}
    </style>
    <main class="main">

    <!-- Hero Section -->
    <section id="hero" class="hero section">

      <img src="{% static '/img/hero-bg.jpg' %}" alt="" data-aos="fade-in">

   <div class="container">
  <h2 data-aos="fade-up" data-aos-delay="100">
    Учись сегодня,<br>возглавляй завтра
  </h2>
  <p data-aos="fade-up" data-aos-delay="200">
    Мы предлагаем уникальную систему накопления баллов за активное участие в жизни общежития и университета.
  </p>
  <div class="d-flex mt-4" data-aos="fade-up" data-aos-delay="300">
    <a href="{% url 'student_list' %}" class="btn-get-started">Студенты</a>
  </div>
</div>


    </section><!-- /Hero Section -->

    <!-- About Section -->
    <section id="about" class="about section">

      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-up" data-aos-delay="100">
            <img src="{% static 'img/about.jpg' %}" class="img-fluid" alt="">
          </div>

<div class="col-lg-6 order-2 order-lg-1 content" data-aos="fade-up" data-aos-delay="200">
    <h3>Преимущества участия в бальной системе общежития</h3>
    <p class="fst-italic">
      Наша система накопления баллов позволяет студентам не только активно участвовать в жизни университета, но и получать за это заслуженные бонусы.
    </p>
    <ul>
      <li><i class="bi bi-check-circle"></i> <span>Повышение ответственности и активности среди студентов.</span></li>
      <li><i class="bi bi-check-circle"></i> <span>Возможность получить преференции при заселении в следующем учебном году.</span></li>
      <li><i class="bi bi-check-circle"></i> <span>Накопление баллов за участие в мероприятиях общежития и волонтёрских акциях, что положительно сказывается на общественной и учебной активности студентов.</span></li>
    </ul>
    <a href="{% url 'student-statistics' %}" class="read-more"><span>Статистика</span><i class="bi bi-arrow-right"></i></a>
</div>


        </div>

      </div>

    </section><!-- /About Section -->
    
    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
           <div class="col-lg-8">
  <h1>Мероприятия и Баллы</h1>
  <p class="mb-0">Принимайте активное участие в жизни общежития и получайте баллы, которые могут быть использованы для улучшения условий проживания или получения привилегий. Участие в мероприятиях не только способствует вашему личностному росту, но и приносит дополнительные бонусы в вашу студенческую жизнь.</p>
</div>

          </div>
        </div>
      </div>
    
    </div><!-- End Page Title -->

    <!-- Events Section -->
 <section id="news" class="news section">
  <div class="container" data-aos="fade-up">
    <div class="row">
      {% for news in news_list %}
        <div class="col-md-6 d-flex align-items-stretch news-card">
          <div class="card">
            {% if news.images %}
              <div class="card-img">
                <img src="{{ news.images.url }}" alt="{{ news.title }}"> {{ news.images.url }}
              </div>
            {% endif %}
            <div class="card-body">
              <p class="fst-italic text-center">{{ news.date|date:"l, F d, Y at H:i" }}</p>
              <p class="card-text">{{ news.content|truncatewords:30 }}</p>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:2 and not forloop.last %}
          </div><div class="row">
        {% endif %}
      {% empty %}
        <div class="col-12">
          <div class="alert alert-info" role="alert">
            Новостей пока нет.
          </div>
        </div><br><br>
      {% endfor %}
    </div>
  </div>
</section>
<!-- /News Section -->

{% endblock %}

templates/statistics.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Студенты и Баллы</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
<style>
    .table a {
        color: #28a745; /* Зеленый цвет Bootstrap */
        text-decoration: none; /* Убираем подчеркивание */
    }
    .table a:hover {
        color: #155724; /* Темно-зеленый цвет при наведении */
        text-decoration: underline; /* Добавляем подчеркивание при наведении */
    }
</style>
</head>
<body>
<div class="container mt-4">
    <h2>Список студентов</h2>
<form method="get" class="mb-4">
    <div class="row g-3 align-items-center">
        <div class="col">
            <label for="dormitory" class="col-form-label">Общежитие</label>
            <select id="dormitory" name="dormitory" class="form-select">
                <option value="">Все</option>
                {% for dorm in dormitories %}
                <option value="{{ dorm.id }}" {% if request.GET.dormitory == dorm.id|stringformat:"s" %}selected{% endif %}>
                    {{ dorm.name }}
                </option>
                {% endfor %}
            </select>
        </div>
        <div class="col">
            <label for="group" class="col-form-label">Группа</label>
            <input type="text" id="group" name="group" class="form-control" value="{{ request.GET.group }}">
        </div>
        <div class="col">
            <label for="room" class="col-form-label">Комната</label>
            <input type="text" id="room" name="room" class="form-control" value="{{ request.GET.room }}">
        </div>
        <div class="col">
            <button type="submit" class="btn btn-getstarted mt-4">Фильтровать</button>
        </div>
    </div>
</form>
    <table class="table">
        {% with request.GET.sort as current_sort %}
    {% with request.GET.dir as current_dir %}
        <thead>
            <tr>
                <th><a href="?sort=full_name{% if current_sort == 'full_name' and current_dir != 'desc' %}&dir=desc{% endif %}">ФИО</a></th>
                <th><a href="?sort=institute{% if current_sort == 'institute' and current_dir != 'desc' %}&dir=desc{% endif %}">Институт</a></th>
                <th><a href="?sort=group{% if current_sort == 'group' and current_dir != 'desc' %}&dir=desc{% endif %}">Группа</a></th>
                <th><a href="?sort=room{% if current_sort == 'room' and current_dir != 'desc' %}&dir=desc{% endif %}">Комната</a></th>
                <th><a href="?sort=total_points{% if current_sort == 'total_points' and current_dir != 'desc' %}&dir=desc{% endif %}">Баллы</a></th>
            </tr>
        </thead>
    {% endwith %}
{% endwith %}
        <tbody>
            {% for student in students %}
            <tr>
                <td><a href="{% url 'student-dossier' student.id %}">{{ student.full_name }}</a></td>
                <td>{{ student.institute }}</td>
                <td>{{ student.group }}</td>
                <td>{{ student.room }}</td>
                <td>{{ student.total_points }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">Студенты не найдены.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

templates/student_dossier.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-3">Студент: {{ student.full_name }}</h1>

    <!-- Карточка с информацией о студенте -->
    <div class="card mb-3">
        <div class="card-header">
            Информация
        </div>
<div class="card-body">
    <p class="card-text">Институт: {{ student.institute }}</p>
    <p class="card-text">Группа: {{ student.group }}</p>
    <p class="card-text">Комната: {{ student.room }}</p>
 <p class="card-text">Баллы: {{ student.total_points }} (Адм: {{ student.total_admin_points }}; ССО: {{ student.total_sso_points }})</p>
<button type="button" class="btn {% if ranking_position <= 10 %}btn-success{% elif ranking_position > 10 and ranking_position <= middle_index %}btn-primary{% elif ranking_position > red_threshold %}btn-danger{% else %}btn-warning{% endif %}">
    Место: {{ ranking_position }} из {{ total_students }}
</button>

</div>

    </div>

    <!-- Карточка с историей баллов -->
    <div class="card">
        <div class="card-header">
            История баллов
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Событие</th>
                        <th>Баллы</th>
                        <th>Дата</th>
                    </tr>
                </thead>
                <tbody>
                    {% for history in points_history %}
                    <tr>
                        <td>{{ history.event.name }}</td>
                         <td>{{ history.event.get_event_type_display }}</td>
                        <td>{{ history.event.points }}</td>
                        <td>{{ history.date|date:"Y-m-d H:i" }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">История баллов не найдена.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/students.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Студенты и Баллы</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>
<body>

<div class="container mt-4">
    <h2>Список студентов</h2>
    <table class="table">
        <thead>
            <tr>
                <th>ФИО</th>
                <th>Институт</th>
                <th>Группа</th>
                <th>Комната</th>
                <th>Баллы</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td><a href="{% url 'student-dossier' student.id %}">{{ student.full_name }}</a></td>
                <td>{{ student.institute }}</td>
                <td>{{ student.group }}</td>
                <td>{{ student.room }}</td>
                <td>{{ student.total_points }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">Студенты не найдены.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}